<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\fontatlas.png" />
    <None Remove="Resources\palettes.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\fontatlas.png" />
    <EmbeddedResource Include="Resources\palettes.json" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Sdcb.Arithmetic.Mpfr" Version="4.2.1" />
	<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
	<PackageReference Include="Spectre.Console" Version="0.55.2" />
	<PackageReference Include="Watson" Version="7.0.11" />
  </ItemGroup>
</Project>
